version: "3"
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PROTEUS_BOT_TOKEN
      - PROTEUS_PROJECT_ID
      - PROTEUS_TOPIC_DISCORD_ON_MESSAGE
    image: proteusbot/event_service